'use client';

import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Button } from '@/components/ui/button';
import Link from 'next/link';
import Sidebar from '@/components/Sidebar';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} flex antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

import { SidebarProvider, useSidebar } from '@/context/SidebarContext';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} flex antialiased`}
      >
        <SidebarProvider>
          <Sidebar />
          <MainContent>{children}</MainContent>
        </SidebarProvider>
      </body>
    </html>
  );
}

function MainContent({ children }) {
  const { isCollapsed } = useSidebar();

  return (
    <div className={`flex-1 transition-all ${isCollapsed ? 'ml-20' : 'ml-60'}`}>
      <Navbar />
      <main className="p-4">{children}</main>
    </div>
  );
}

function Navbar() {
  return (
    <nav className="bg-blue-600 text-white p-4 flex justify-between items-center">
      <h1 className="text-xl font-bold">Task Manager</h1>
      <Link href="/settings" className="hover:underline">
        Settings
      </Link>
    </nav>
  );
}
